version: '2.2'
services:
  lab:
    image: jupyter/pyspark-notebook
    command: jupyter lab --no-browser --ServerApp.token='' --ServerApp.password=''
    ports:
     - 8888:8888
     - 4040:4040
    volumes: 
     - ./:/home/jovyan/work

